version: "3.8"

services:
  server:
    build: .
    container_name: service
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: "bill"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    depends_on:
      - postgres

  postgres:
    image: postgres:12.9
    container_name: db
    environment:
      POSTGRES_DB: "bill"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./pkg/database/createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
    ports:
    - 5432:5432